require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GroupBuyInsController do

  # This should return the minimal set of attributes required to create a valid
  # GroupBuyIn. As you add validations to GroupBuyIn, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GroupBuyInsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all group_buy_ins as @group_buy_ins" do
      group_buy_in = GroupBuyIn.create! valid_attributes
      get :index, {}, valid_session
      assigns(:group_buy_ins).should eq([group_buy_in])
    end
  end

  describe "GET show" do
    it "assigns the requested group_buy_in as @group_buy_in" do
      group_buy_in = GroupBuyIn.create! valid_attributes
      get :show, {:id => group_buy_in.to_param}, valid_session
      assigns(:group_buy_in).should eq(group_buy_in)
    end
  end

  describe "GET new" do
    it "assigns a new group_buy_in as @group_buy_in" do
      get :new, {}, valid_session
      assigns(:group_buy_in).should be_a_new(GroupBuyIn)
    end
  end

  describe "GET edit" do
    it "assigns the requested group_buy_in as @group_buy_in" do
      group_buy_in = GroupBuyIn.create! valid_attributes
      get :edit, {:id => group_buy_in.to_param}, valid_session
      assigns(:group_buy_in).should eq(group_buy_in)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GroupBuyIn" do
        expect {
          post :create, {:group_buy_in => valid_attributes}, valid_session
        }.to change(GroupBuyIn, :count).by(1)
      end

      it "assigns a newly created group_buy_in as @group_buy_in" do
        post :create, {:group_buy_in => valid_attributes}, valid_session
        assigns(:group_buy_in).should be_a(GroupBuyIn)
        assigns(:group_buy_in).should be_persisted
      end

      it "redirects to the created group_buy_in" do
        post :create, {:group_buy_in => valid_attributes}, valid_session
        response.should redirect_to(GroupBuyIn.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved group_buy_in as @group_buy_in" do
        # Trigger the behavior that occurs when invalid params are submitted
        GroupBuyIn.any_instance.stub(:save).and_return(false)
        post :create, {:group_buy_in => {}}, valid_session
        assigns(:group_buy_in).should be_a_new(GroupBuyIn)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GroupBuyIn.any_instance.stub(:save).and_return(false)
        post :create, {:group_buy_in => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested group_buy_in" do
        group_buy_in = GroupBuyIn.create! valid_attributes
        # Assuming there are no other group_buy_ins in the database, this
        # specifies that the GroupBuyIn created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GroupBuyIn.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => group_buy_in.to_param, :group_buy_in => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested group_buy_in as @group_buy_in" do
        group_buy_in = GroupBuyIn.create! valid_attributes
        put :update, {:id => group_buy_in.to_param, :group_buy_in => valid_attributes}, valid_session
        assigns(:group_buy_in).should eq(group_buy_in)
      end

      it "redirects to the group_buy_in" do
        group_buy_in = GroupBuyIn.create! valid_attributes
        put :update, {:id => group_buy_in.to_param, :group_buy_in => valid_attributes}, valid_session
        response.should redirect_to(group_buy_in)
      end
    end

    describe "with invalid params" do
      it "assigns the group_buy_in as @group_buy_in" do
        group_buy_in = GroupBuyIn.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GroupBuyIn.any_instance.stub(:save).and_return(false)
        put :update, {:id => group_buy_in.to_param, :group_buy_in => {}}, valid_session
        assigns(:group_buy_in).should eq(group_buy_in)
      end

      it "re-renders the 'edit' template" do
        group_buy_in = GroupBuyIn.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GroupBuyIn.any_instance.stub(:save).and_return(false)
        put :update, {:id => group_buy_in.to_param, :group_buy_in => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested group_buy_in" do
      group_buy_in = GroupBuyIn.create! valid_attributes
      expect {
        delete :destroy, {:id => group_buy_in.to_param}, valid_session
      }.to change(GroupBuyIn, :count).by(-1)
    end

    it "redirects to the group_buy_ins list" do
      group_buy_in = GroupBuyIn.create! valid_attributes
      delete :destroy, {:id => group_buy_in.to_param}, valid_session
      response.should redirect_to(group_buy_ins_url)
    end
  end

end
