require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PrizeCodesController do

  # This should return the minimal set of attributes required to create a valid
  # PrizeCode. As you add validations to PrizeCode, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrizeCodesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all prize_codes as @prize_codes" do
      prize_code = PrizeCode.create! valid_attributes
      get :index, {}, valid_session
      assigns(:prize_codes).should eq([prize_code])
    end
  end

  describe "GET show" do
    it "assigns the requested prize_code as @prize_code" do
      prize_code = PrizeCode.create! valid_attributes
      get :show, {:id => prize_code.to_param}, valid_session
      assigns(:prize_code).should eq(prize_code)
    end
  end

  describe "GET new" do
    it "assigns a new prize_code as @prize_code" do
      get :new, {}, valid_session
      assigns(:prize_code).should be_a_new(PrizeCode)
    end
  end

  describe "GET edit" do
    it "assigns the requested prize_code as @prize_code" do
      prize_code = PrizeCode.create! valid_attributes
      get :edit, {:id => prize_code.to_param}, valid_session
      assigns(:prize_code).should eq(prize_code)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PrizeCode" do
        expect {
          post :create, {:prize_code => valid_attributes}, valid_session
        }.to change(PrizeCode, :count).by(1)
      end

      it "assigns a newly created prize_code as @prize_code" do
        post :create, {:prize_code => valid_attributes}, valid_session
        assigns(:prize_code).should be_a(PrizeCode)
        assigns(:prize_code).should be_persisted
      end

      it "redirects to the created prize_code" do
        post :create, {:prize_code => valid_attributes}, valid_session
        response.should redirect_to(PrizeCode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prize_code as @prize_code" do
        # Trigger the behavior that occurs when invalid params are submitted
        PrizeCode.any_instance.stub(:save).and_return(false)
        post :create, {:prize_code => {}}, valid_session
        assigns(:prize_code).should be_a_new(PrizeCode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PrizeCode.any_instance.stub(:save).and_return(false)
        post :create, {:prize_code => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prize_code" do
        prize_code = PrizeCode.create! valid_attributes
        # Assuming there are no other prize_codes in the database, this
        # specifies that the PrizeCode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PrizeCode.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => prize_code.to_param, :prize_code => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested prize_code as @prize_code" do
        prize_code = PrizeCode.create! valid_attributes
        put :update, {:id => prize_code.to_param, :prize_code => valid_attributes}, valid_session
        assigns(:prize_code).should eq(prize_code)
      end

      it "redirects to the prize_code" do
        prize_code = PrizeCode.create! valid_attributes
        put :update, {:id => prize_code.to_param, :prize_code => valid_attributes}, valid_session
        response.should redirect_to(prize_code)
      end
    end

    describe "with invalid params" do
      it "assigns the prize_code as @prize_code" do
        prize_code = PrizeCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PrizeCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => prize_code.to_param, :prize_code => {}}, valid_session
        assigns(:prize_code).should eq(prize_code)
      end

      it "re-renders the 'edit' template" do
        prize_code = PrizeCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PrizeCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => prize_code.to_param, :prize_code => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prize_code" do
      prize_code = PrizeCode.create! valid_attributes
      expect {
        delete :destroy, {:id => prize_code.to_param}, valid_session
      }.to change(PrizeCode, :count).by(-1)
    end

    it "redirects to the prize_codes list" do
      prize_code = PrizeCode.create! valid_attributes
      delete :destroy, {:id => prize_code.to_param}, valid_session
      response.should redirect_to(prize_codes_url)
    end
  end

end
